# Generated by Django 2.2 on 2021-12-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transforum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transtreenode',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
