# Generated by Django 2.2 on 2021-12-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transforum', '0002_auto_20211208_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transtreenode',
            name='content_source',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
