# Generated by Django 2.2 on 2021-12-08 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transforum', '0004_auto_20211208_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transtreenode',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
