# Generated by Django 2.2 on 2021-12-08 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transforum', '0005_auto_20211208_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transtreenode',
            name='author',
        ),
        migrations.AddField(
            model_name='transtreenode',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
