
curl --location --request POST 'http://127.0.0.1:8000/api/token/' \
--header 'Content-Type: application/json' \
--data-raw '{
    "username": 
        "wzc"
    ,
    "password": 
        "Wzc2896833"
    
}'